version: '3.8'

services:
#  server:
#    container_name: space-server
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "1337:1337"
#    volumes:
#      - .:/usr/app
#    environment:
#      APP_KEYS: ${APP_KEYS}
#      API_TOKEN_SALT: ${API_TOKEN_SALT}
#      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
#      TRANSFER_TOKEN_SALT: ${TRANSFER_TOKEN_SALT}
#      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
#      DATABASE_USERNAME: ${DATABASE_USERNAME}
#      DATABASE_NAME: ${DATABASE_NAME}
#      DATABASE_HOST: ${DATABASE_HOST}
#      DATABASE_CLIENT: ${DATABASE_CLIENT}
#      DATABASE_PORT: ${DATABASE_PORT}
#      DATABASE_SSL: ${DATABASE_SSL}
#    networks:
#      - strapi
  db:
    container_name: space-database
    image: postgres:14.1-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - strapi
networks:
  strapi:
volumes:
  db:
